USE locodocu;

DROP TABLE IF EXISTS UserRoleRelation;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;

CREATE TABLE [Users] (
    [Id] INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [Email] NVARCHAR(255) NOT NULL UNIQUE,
    [Phone] VARCHAR(20),
    [Disabled] DATETIME2
);

CREATE TABLE [Roles] (
    [Id] INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE [UserRoleRelation] (
    [Id] INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [UserId] INT FOREIGN KEY REFERENCES [Users](Id),
    [RoleId] INT FOREIGN KEY REFERENCES [Roles](Id)
);